# Generated by Django 3.1.4 on 2020-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.CharField(max_length=99)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.IntegerField()),
                ('folder', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('github', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.github')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('javascript', models.IntegerField()),
                ('java', models.IntegerField()),
                ('python', models.IntegerField()),
                ('php', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('github', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.github')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
